### ISSUE TITLE
Cannot decrypt using ByteArrayInputStream as input stream

### ISSUE THREAD

**Issue by gd-iistomin** [neuhalje/bouncy-gpg#15]
Hello, I ran into the following issue:
I need to decrypt some secret data which is just encrypted and stored in memory as byte array. I have the following error:
```
Exception in thread "main" java.io.EOFException: premature end of stream in PartialInputStream
	at org.bouncycastle.bcpg.BCPGInputStream$PartialInputStream.read(Unknown Source)
	at org.bouncycastle.bcpg.BCPGInputStream.read(Unknown Source)
	at org.bouncycastle.bcpg.SymmetricEncIntegrityPacket.<init>(Unknown Source)
	at org.bouncycastle.bcpg.BCPGInputStream.readPacket(Unknown Source)
	at org.bouncycastle.openpgp.PGPEncryptedDataList.<init>(Unknown Source)
	at org.bouncycastle.openpgp.PGPObjectFactory.nextObject(Unknown Source)
	at name.neuhalfen.projects.crypto.bouncycastle.openpgp.decrypting.DecryptionStreamFactory.nextDecryptedStream(DecryptionStreamFactory.java:78)
	at name.neuhalfen.projects.crypto.bouncycastle.openpgp.decrypting.DecryptionStreamFactory.wrapWithDecryptAndVerify(DecryptionStreamFactory.java:58)
	at name.neuhalfen.projects.crypto.bouncycastle.openpgp.BuildDecryptionInputStreamAPI$Validation$Builder.fromEncryptedInputStream(BuildDecryptionInputStreamAPI.java:170)
	at Main.main(Main.java:61)
```
My source code:
```
byte[] bytes;
        try (
                final ByteArrayOutputStream byteOutput = new ByteArrayOutputStream();

                final OutputStream outputStream = BouncyGPG
                        .encryptToStream()
                        .withConfig(keyringConfigInMemoryForSender())
                        .withStrongAlgorithms()
                        .toRecipient("recipient@example.com")
                        .andSignWith("sender@example.com")
                        .binaryOutput()
                        .andWriteTo(byteOutput);

                final FileInputStream is = new FileInputStream("tmp/plaintext.txt")
        ) {
            Streams.pipeAll(is, outputStream);
            bytes = byteOutput.toByteArray();
        }


        try (
                final ByteArrayInputStream cipherTextStream = new ByteArrayInputStream(bytes);

                final FileOutputStream fileOutput = new FileOutputStream("tmp/decrypted.txt");
                final BufferedOutputStream bufferedOut = new BufferedOutputStream(fileOutput);

                final InputStream plaintextStream = BouncyGPG
                        .decryptAndVerifyStream()
                        .withConfig(keyringConfigInMemoryForRecipient())
                        .andIgnoreSignatures()
                        .fromEncryptedInputStream(cipherTextStream)

        ) {
            Streams.pipeAll(plaintextStream, bufferedOut);
        }
    }
```
Have you any ideas what I'm doing wrong, or it is an expected behaviour?

**Comment by neuhalje** [comment]
I can reproduce your result.

The root cause is that the encryption stream has to write data (e.g. the signature, but other things as well) _after_ all data from the `InputStream` has been consumed. Technically this has to be done in the encryptions stream `close()` method.

Normally a well placed `outputStream.close()` would solve your problem:

```java
  try (
         ...
    ) {
      Streams.pipeAll(is, outputStream);
      outputStream.close(); // here
      bytes = byteOutput.toByteArray();
    }
```

Alas, the current version seems to have a bug that makes `close()`  not idempotent and will raise an error if the stream is closed twice.  I have changed this in commit 3226cb6.

Until the next version is released move `byteOutput` outside of the _try-with-resources_:

```java
...
    final ByteArrayOutputStream byteOutput = new ByteArrayOutputStream();
    byte[] bytes;
    try (

        final OutputStream outputStream = BouncyGPG
            .encryptToStream()
            ...
            .andWriteTo(byteOutput);

        final ByteArrayInputStream is = new ByteArrayInputStream(expectedPlaintext)
    ) {
      Streams.pipeAll(is, outputStream);
    }
    bytes = byteOutput.toByteArray();
    byteOutput.close();
...
```
